// src/pages/onboarding/CardCustomization.vue
<template>
  <view class="card-customization-page">
    <!-- Header -->
    <view class="header-section">
      <view class="icon-wrapper">
        <text class="header-icon">🎨</text>
      </view>
      <text class="header-title">Customize Your Card</text>
      <text class="header-subtitle">Choose colors and style for your business card</text>
    </view>

    <view class="content-section">
      <!-- Preview Card -->
      <view class="preview-card">
        <view class="preview-header">
          <text class="sparkle-icon">✨</text>
          <text class="preview-title">Preview</text>
        </view>
        <view :class="['mini-card', getStyleClass()]">
          <view class="mini-card-content">
            <view :class="['mini-avatar', getGradientClass()]">
              <text class="avatar-emoji">👤</text>
            </view>
            <view class="mini-info">
              <text :class="['mini-name', customization.theme === 'classic' ? 'text-dark' : '']">Your Name</text>
              <text class="mini-title" :style="{ color: customization.primaryColor }">Your Title</text>
              <text class="mini-company" :style="{ color: customization.secondaryColor }">Your Company</text>
            </view>
          </view>
        </view>
      </view>

      <!-- Theme Selection -->
      <view class="form-card">
        <text class="card-title">Theme</text>
        <view class="theme-grid">
          <button
            :class="['theme-btn', customization.theme === 'dark' ? 'active' : '']"
            @click="customization.theme = 'dark'"
          >
            <text>Dark Mode</text>
          </button>
          <button
            :class="['theme-btn', customization.theme === 'light' ? 'active' : '']"
            @click="customization.theme = 'light'"
          >
            <text>Light Mode</text>
          </button>
        </view>
      </view>

      <!-- Color Selection -->
      <view class="form-card">
        <text class="card-title">Color Theme</text>
        <view class="color-grid">
          <button
            v-for="theme in colorThemes"
            :key="theme.id"
            :class="['color-btn', selectedColorTheme.id === theme.id ? 'selected' : '']"
            @click="selectColorTheme(theme)"
          >
            <view :class="['color-circle', theme.gradient]"></view>
            <text v-if="selectedColorTheme.id === theme.id" class="check-icon">✓</text>
            <text class="color-name">{{ theme.name }}</text>
          </button>
        </view>
      </view>

      <!-- Style Selection -->
      <view class="form-card">
        <text class="card-title">Card Style</text>
        <view class="style-list">
          <button
            v-for="style in cardStyles"
            :key="style.id"
            :class="['style-btn', customization.style === style.id ? 'selected' : '']"
            @click="customization.style = style.id"
          >
            <view class="style-header">
              <text class="style-name">{{ style.name }}</text>
              <text v-if="customization.style === style.id" class="check-icon">✓</text>
            </view>
            <text class="style-desc">{{ style.description }}</text>
          </button>
        </view>
      </view>

      <!-- Action Buttons -->
      <button class="submit-btn" @click="handleSubmit">
        <text>Create My Card</text>
        <text class="arrow-icon">→</text>
      </button>

      <button v-if="onBack" class="back-btn" @click="handleBack">
        <text>Back</text>
      </button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

interface CardCustomization {
  theme: 'dark' | 'light'
  primaryColor: string
  secondaryColor: string
  style: 'modern' | 'classic' | 'minimal' | 'gradient'
}

const emit = defineEmits<{
  complete: [customization: CardCustomization]
  back: []
}>()

const props = defineProps<{
  onBack?: () => void
}>()

const colorThemes = [
  { id: 'yellow-blue', name: 'Yellow & Blue', primary: '#FACC15', secondary: '#38BDF8', gradient: 'gradient-yb' },
  { id: 'purple-pink', name: 'Purple & Pink', primary: '#A855F7', secondary: '#EC4899', gradient: 'gradient-pp' },
  { id: 'green-teal', name: 'Green & Teal', primary: '#10B981', secondary: '#14B8A6', gradient: 'gradient-gt' },
  { id: 'orange-red', name: 'Orange & Red', primary: '#F59E0B', secondary: '#EF4444', gradient: 'gradient-or' },
  { id: 'blue-indigo', name: 'Blue & Indigo', primary: '#3B82F6', secondary: '#6366F1', gradient: 'gradient-bi' },
  { id: 'cyan-blue', name: 'Cyan & Blue', primary: '#06B6D4', secondary: '#0EA5E9', gradient: 'gradient-cb' },
]

const cardStyles = [
  { id: 'modern', name: 'Modern', description: 'Glassmorphism with gradient accents' },
  { id: 'classic', name: 'Classic', description: 'Clean and professional' },
  { id: 'minimal', name: 'Minimal', description: 'Simple and elegant' },
  { id: 'gradient', name: 'Gradient', description: 'Bold gradient background' },
]

const customization = ref<CardCustomization>({
  theme: 'dark',
  primaryColor: '#FACC15',
  secondaryColor: '#38BDF8',
  style: 'modern',
})

const selectedColorTheme = computed(() => {
  return colorThemes.find((t) => t.primary === customization.value.primaryColor) || colorThemes[0]
})

const selectColorTheme = (theme: typeof colorThemes[0]) => {
  customization.value.primaryColor = theme.primary
  customization.value.secondaryColor = theme.secondary
}

const getStyleClass = () => {
  switch (customization.value.style) {
    case 'modern':
      return 'style-modern'
    case 'classic':
      return 'style-classic'
    case 'minimal':
      return 'style-minimal'
    case 'gradient':
      return `style-gradient ${selectedColorTheme.value.gradient}`
    default:
      return 'style-modern'
  }
}

const getGradientClass = () => {
  return `gradient-${selectedColorTheme.value.id}`
}

const handleSubmit = () => {
  emit('complete', customization.value)
}

const handleBack = () => {
  if (props.onBack) {
    props.onBack()
  } else {
    emit('back')
  }
}
</script>

<style lang="scss" scoped>
@import '../../styles/designTokens.scss';

.card-customization-page {
  min-height: 100vh;
  background: #020617;
  padding: $spacing-xl $spacing-md;
  padding-bottom: 192rpx;
}

.header-section {
  text-align: center;
  margin-bottom: $spacing-lg;
}

.icon-wrapper {
  width: 128rpx;
  height: 128rpx;
  border-radius: 50%;
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto $spacing-md;
}

.header-icon {
  font-size: 64rpx;
}

.header-title {
  font-size: $font-size-xl;
  color: $color-text-primary;
  font-weight: $font-weight-bold;
  display: block;
  margin-bottom: $spacing-sm;
}

.header-subtitle {
  font-size: $font-size-sm;
  color: rgba(255, 255, 255, 0.6);
}

.content-section {
  max-width: 600rpx;
  margin: 0 auto;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
  
  // Desktop/Laptop styles
  // #ifdef H5
  @media (min-width: 768px) {
    max-width: 700px;
  }
  
  @media (min-width: 1024px) {
    max-width: 800px;
  }
  // #endif
}

.preview-card {
  padding: $spacing-lg;
  border-radius: 48rpx;
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.4);
}

.preview-header {
  display: flex;
  align-items: center;
  gap: $spacing-sm;
  margin-bottom: $spacing-md;
}

.sparkle-icon {
  font-size: 40rpx;
  color: #FACC15;
}

.preview-title {
  font-size: $font-size-sm;
  color: $color-text-primary;
  font-weight: $font-weight-semibold;
}

.mini-card {
  padding: $spacing-md;
  border-radius: 40rpx;
  box-shadow: 0 4rpx 12rpx rgba(0, 0, 0, 0.2);
}

.style-modern {
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
}

.style-classic {
  background: rgba(255, 255, 255, 0.95);
  border: 1px solid rgba(0, 0, 0, 0.1);
}

.style-minimal {
  background: rgba(15, 23, 42, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.05);
}

.style-gradient {
  border: none;
}

.gradient-yb { background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%); }
.gradient-pp { background: linear-gradient(135deg, #A855F7 0%, #EC4899 100%); }
.gradient-gt { background: linear-gradient(135deg, #10B981 0%, #14B8A6 100%); }
.gradient-or { background: linear-gradient(135deg, #F59E0B 0%, #EF4444 100%); }
.gradient-bi { background: linear-gradient(135deg, #3B82F6 0%, #6366F1 100%); }
.gradient-cb { background: linear-gradient(135deg, #06B6D4 0%, #0EA5E9 100%); }

.mini-card-content {
  display: flex;
  align-items: flex-start;
  gap: $spacing-md;
}

.mini-avatar {
  width: 128rpx;
  height: 128rpx;
  border-radius: 50%;
  padding: 4rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.mini-avatar.gradient-yb { background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%); }
.mini-avatar.gradient-pp { background: linear-gradient(135deg, #A855F7 0%, #EC4899 100%); }
.mini-avatar.gradient-gt { background: linear-gradient(135deg, #10B981 0%, #14B8A6 100%); }
.mini-avatar.gradient-or { background: linear-gradient(135deg, #F59E0B 0%, #EF4444 100%); }
.mini-avatar.gradient-bi { background: linear-gradient(135deg, #3B82F6 0%, #6366F1 100%); }
.mini-avatar.gradient-cb { background: linear-gradient(135deg, #06B6D4 0%, #0EA5E9 100%); }

.avatar-emoji {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  background: #020617;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 48rpx;
}

.mini-info {
  flex: 1;
}

.mini-name {
  font-size: $font-size-base;
  color: $color-text-primary;
  display: block;
  margin-bottom: 8rpx;
  font-weight: $font-weight-semibold;
}

.mini-name.text-dark {
  color: #020617;
}

.mini-title {
  font-size: $font-size-sm;
  display: block;
  margin-bottom: 4rpx;
}

.mini-company {
  font-size: $font-size-xs;
}

.form-card {
  padding: $spacing-lg;
  border-radius: 48rpx;
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.4);
}

.card-title {
  font-size: $font-size-sm;
  color: $color-text-primary;
  font-weight: $font-weight-semibold;
  display: block;
  margin-bottom: $spacing-md;
}

.theme-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: $spacing-md;
}

.theme-btn {
  padding: $spacing-md;
  border-radius: 24rpx;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: $color-text-primary;
  font-size: $font-size-sm;
  transition: all 0.3s ease;
}

.theme-btn.active {
  background: #FACC15;
  color: #020617;
  border-color: #FACC15;
}

.color-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: $spacing-md;
}

.color-btn {
  padding: $spacing-md;
  border-radius: 24rpx;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: $spacing-sm;
  transition: all 0.3s ease;
}

.color-btn.selected {
  background: rgba(255, 255, 255, 0.1);
  border: 2px solid rgba(255, 255, 255, 0.3);
}

.color-circle {
  width: 64rpx;
  height: 64rpx;
  border-radius: 50%;
}

.color-name {
  font-size: $font-size-xs;
  color: $color-text-primary;
}

.check-icon {
  font-size: 40rpx;
  color: #FACC15;
  position: absolute;
  right: $spacing-sm;
  top: $spacing-sm;
}

.style-list {
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
}

.style-btn {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  text-align: left;
  transition: all 0.3s ease;
}

.style-btn.selected {
  background: rgba(255, 255, 255, 0.1);
  border: 2px solid #FACC15;
}

.style-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8rpx;
}

.style-name {
  font-size: $font-size-sm;
  color: $color-text-primary;
  font-weight: $font-weight-semibold;
}

.style-desc {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.6);
}

.submit-btn {
  width: 100%;
  padding: 18rpx 28rpx;
  border-radius: 24rpx;
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  color: #020617;
  font-size: $font-size-base;
  font-weight: $font-weight-medium;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: $spacing-sm;
  transition: all 0.3s ease;
  box-shadow: 0 4rpx 12rpx rgba(250, 204, 21, 0.4);
  min-height: 72rpx;
  box-sizing: border-box;
}

.submit-btn:active {
  transform: scale(0.98);
}

.arrow-icon {
  font-size: 40rpx;
}

.back-btn {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  color: rgba(255, 255, 255, 0.6);
  font-size: $font-size-sm;
  transition: all 0.3s ease;
}

.back-btn:active {
  color: $color-text-primary;
  background: rgba(255, 255, 255, 0.05);
}
</style>

// figma-import/src/components/onboarding/CardCustomization.tsx
import { useState } from 'react';
import { Palette, Check, Sparkles, ArrowRight } from 'lucide-react';

interface CardCustomizationProps {
  onComplete: (customization: CardCustomization) => void;
  onBack?: () => void;
}

interface CardCustomization {
  theme: 'dark' | 'light';
  primaryColor: string;
  secondaryColor: string;
  style: 'modern' | 'classic' | 'minimal' | 'gradient';
}

const colorThemes = [
  {
    id: 'yellow-blue',
    name: 'Yellow & Blue',
    primary: '#FACC15',
    secondary: '#38BDF8',
    gradient: 'from-[#FACC15] to-[#38BDF8]',
  },
  {
    id: 'purple-pink',
    name: 'Purple & Pink',
    primary: '#A855F7',
    secondary: '#EC4899',
    gradient: 'from-[#A855F7] to-[#EC4899]',
  },
  {
    id: 'green-teal',
    name: 'Green & Teal',
    primary: '#10B981',
    secondary: '#14B8A6',
    gradient: 'from-[#10B981] to-[#14B8A6]',
  },
  {
    id: 'orange-red',
    name: 'Orange & Red',
    primary: '#F59E0B',
    secondary: '#EF4444',
    gradient: 'from-[#F59E0B] to-[#EF4444]',
  },
  {
    id: 'blue-indigo',
    name: 'Blue & Indigo',
    primary: '#3B82F6',
    secondary: '#6366F1',
    gradient: 'from-[#3B82F6] to-[#6366F1]',
  },
  {
    id: 'cyan-blue',
    name: 'Cyan & Blue',
    primary: '#06B6D4',
    secondary: '#0EA5E9',
    gradient: 'from-[#06B6D4] to-[#0EA5E9]',
  },
];

const cardStyles = [
  {
    id: 'modern',
    name: 'Modern',
    description: 'Glassmorphism with gradient accents',
    preview: 'rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10',
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Clean and professional',
    preview: 'rounded-xl bg-white/95 border border-gray-200',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Simple and elegant',
    preview: 'rounded-lg bg-[#0F172A]/60 border border-white/5',
  },
  {
    id: 'gradient',
    name: 'Gradient',
    description: 'Bold gradient background',
    preview: 'rounded-[24px] bg-gradient-to-br border-none',
  },
];

export function CardCustomization({ onComplete, onBack }: CardCustomizationProps) {
  const [customization, setCustomization] = useState<CardCustomization>({
    theme: 'dark',
    primaryColor: '#FACC15',
    secondaryColor: '#38BDF8',
    style: 'modern',
  });

  const selectedColorTheme = colorThemes.find(
    (t) => t.primary === customization.primaryColor
  ) || colorThemes[0];

  const handleSubmit = () => {
    onComplete(customization);
  };

  return (
    <div className="min-h-screen bg-[#020617] px-4 py-8">
      <div className="max-w-md mx-auto">
        {/* Header */}
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-br from-[#FACC15] to-[#38BDF8] mb-4">
            <Palette className="w-8 h-8 text-[#020617]" strokeWidth={1.5} />
          </div>
          <h1 className="text-white text-2xl mb-2">Customize Your Card</h1>
          <p className="text-white/60 text-sm">Choose colors and style for your business card</p>
        </div>

        <div className="space-y-4">
          {/* Preview Card */}
          <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-6 shadow-2xl">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles className="w-5 h-5 text-[#FACC15]" strokeWidth={1.5} />
              <h2 className="text-white text-sm">Preview</h2>
            </div>

            {/* Mini Card Preview */}
            <div
              className={`${
                customization.style === 'modern'
                  ? 'rounded-[20px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10'
                  : customization.style === 'classic'
                  ? 'rounded-xl bg-white/95'
                  : customization.style === 'minimal'
                  ? 'rounded-lg bg-[#0F172A]/60 border border-white/5'
                  : `rounded-[20px] bg-gradient-to-br ${selectedColorTheme.gradient}`
              } p-6 shadow-lg`}
            >
              <div className="flex items-start gap-4">
                <div
                  className={`w-16 h-16 rounded-full bg-gradient-to-br ${selectedColorTheme.gradient} p-1`}
                >
                  <div className="w-full h-full rounded-full bg-[#020617] flex items-center justify-center text-2xl">
                    👤
                  </div>
                </div>
                <div className="flex-1">
                  <h3
                    className={`${
                      customization.style === 'classic' ? 'text-gray-900' : 'text-white'
                    } mb-1`}
                  >
                    Your Name
                  </h3>
                  <p
                    className="text-sm mb-1"
                    style={{ color: customization.primaryColor }}
                  >
                    Your Title
                  </p>
                  <p className="text-xs" style={{ color: customization.secondaryColor }}>
                    Your Company
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Theme Selection */}
          <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-5 shadow-2xl">
            <h2 className="text-white mb-4 text-sm">Theme</h2>
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => setCustomization({ ...customization, theme: 'dark' })}
                className={`py-3 px-4 rounded-xl transition-all ${
                  customization.theme === 'dark'
                    ? 'bg-[#FACC15] text-[#020617] border border-[#FACC15]'
                    : 'bg-white/5 text-white border border-white/10 hover:bg-white/10'
                }`}
              >
                <span className="text-sm">Dark Mode</span>
              </button>
              <button
                onClick={() => setCustomization({ ...customization, theme: 'light' })}
                className={`py-3 px-4 rounded-xl transition-all ${
                  customization.theme === 'light'
                    ? 'bg-[#FACC15] text-[#020617] border border-[#FACC15]'
                    : 'bg-white/5 text-white border border-white/10 hover:bg-white/10'
                }`}
              >
                <span className="text-sm">Light Mode</span>
              </button>
            </div>
          </div>

          {/* Color Selection */}
          <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-5 shadow-2xl">
            <h2 className="text-white mb-4 text-sm">Color Theme</h2>
            <div className="grid grid-cols-2 gap-3">
              {colorThemes.map((theme) => (
                <button
                  key={theme.id}
                  onClick={() =>
                    setCustomization({
                      ...customization,
                      primaryColor: theme.primary,
                      secondaryColor: theme.secondary,
                    })
                  }
                  className={`p-4 rounded-xl transition-all ${
                    selectedColorTheme.id === theme.id
                      ? 'bg-white/10 border-2 border-white/30'
                      : 'bg-white/5 border border-white/10 hover:bg-white/10'
                  }`}
                >
                  <div className="flex items-center gap-3 mb-2">
                    <div
                      className={`w-8 h-8 rounded-full bg-gradient-to-br ${theme.gradient}`}
                    ></div>
                    {selectedColorTheme.id === theme.id && (
                      <Check className="w-5 h-5 text-[#FACC15]" strokeWidth={1.5} />
                    )}
                  </div>
                  <p className="text-white text-xs text-left">{theme.name}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Style Selection */}
          <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-5 shadow-2xl">
            <h2 className="text-white mb-4 text-sm">Card Style</h2>
            <div className="space-y-3">
              {cardStyles.map((style) => (
                <button
                  key={style.id}
                  onClick={() =>
                    setCustomization({
                      ...customization,
                      style: style.id as CardCustomization['style'],
                    })
                  }
                  className={`w-full p-4 rounded-xl transition-all text-left ${
                    customization.style === style.id
                      ? 'bg-white/10 border-2 border-[#FACC15]'
                      : 'bg-white/5 border border-white/10 hover:bg-white/10'
                  }`}
                >
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-white text-sm">{style.name}</h3>
                    {customization.style === style.id && (
                      <Check className="w-5 h-5 text-[#FACC15]" strokeWidth={1.5} />
                    )}
                  </div>
                  <p className="text-white/60 text-xs">{style.description}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Action Buttons */}
          <button
            onClick={handleSubmit}
            className="w-full py-4 rounded-xl bg-gradient-to-r from-[#FACC15] to-[#38BDF8] text-[#020617] hover:opacity-90 transition-all shadow-lg flex items-center justify-center gap-2"
          >
            <span className="font-medium">Create My Card</span>
            <ArrowRight className="w-5 h-5" strokeWidth={1.5} />
          </button>

          {onBack && (
            <button
              onClick={onBack}
              className="w-full py-3 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-all"
            >
              <span className="text-sm">Back</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
