// src/pages/onboarding/CardPhotoCapture.vue
<template>
  <view class="card-photo-capture-page">
    <!-- Header -->
    <view class="header-section">
      <view class="icon-wrapper">
        <text class="header-icon">📷</text>
      </view>
      <text class="header-title">Capture Business Card</text>
      <text class="header-subtitle">Take a photo of your business card or upload from gallery</text>
    </view>

    <!-- Main Card -->
    <view class="main-card">
      <view v-if="!capturedImage" class="upload-section">
        <!-- Upload Area -->
        <view class="upload-area" @click="handleFileSelect">
          <text class="upload-icon">📤</text>
          <text class="upload-text">Click to upload photo</text>
          <text class="upload-hint">or drag and drop</text>
        </view>

        <!-- Camera Button -->
        <button class="action-btn primary" @click="handleFileSelect">
          <text class="btn-icon">📷</text>
          <text>Take Photo</text>
        </button>

        <!-- Upload Button -->
        <button class="action-btn secondary" @click="handleFileSelect">
          <text class="btn-icon">📤</text>
          <text>Upload from Gallery</text>
        </button>

        <!-- Tips -->
        <view class="tips-card">
          <text class="tips-title">📸 Tips for best results:</text>
          <view class="tips-list">
            <text class="tip-item">• Ensure good lighting</text>
            <text class="tip-item">• Keep the card flat and in focus</text>
            <text class="tip-item">• Capture all text clearly</text>
            <text class="tip-item">• Avoid shadows and glare</text>
          </view>
        </view>

        <!-- Skip Button -->
        <button class="skip-btn" @click="handleSkip">
          <text>Skip - Enter Manually</text>
        </button>
      </view>

      <view v-else class="preview-section">
        <!-- Preview -->
        <view class="preview-container">
          <image class="preview-image" :src="capturedImage" mode="aspectFit" />
          <view v-if="isProcessing" class="processing-overlay">
            <view class="spinner"></view>
            <view class="processing-content">
              <text class="sparkle-icon">✨</text>
              <text class="processing-text">AI Processing...</text>
            </view>
            <text class="processing-desc">Extracting information from card</text>
          </view>
        </view>

        <view v-if="!isProcessing" class="preview-actions">
          <button class="action-btn secondary" @click="handleRetake">
            <text class="btn-icon">🔄</text>
            <text>Retake</text>
          </button>
          <button class="action-btn primary" @click="handleConfirm">
            <text class="btn-icon">✓</text>
            <text>Confirm & Process</text>
          </button>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const emit = defineEmits<{
  photoCapture: [imageData: string]
  skip: []
}>()

const capturedImage = ref<string | null>(null)
const isProcessing = ref(false)

const handleFileSelect = () => {
  uni.chooseImage({
    count: 1,
    success: (res) => {
      const tempFilePath = Array.isArray(res.tempFilePaths) ? res.tempFilePaths[0] : res.tempFilePaths
      capturedImage.value = tempFilePath
    },
  })
}

const handleConfirm = () => {
  if (capturedImage.value) {
    isProcessing.value = true
    setTimeout(() => {
      emit('photoCapture', capturedImage.value!)
    }, 2000)
  }
}

const handleRetake = () => {
  capturedImage.value = null
  isProcessing.value = false
}

const handleSkip = () => {
  emit('skip')
}
</script>

<style lang="scss" scoped>
@import '../../styles/designTokens.scss';

.card-photo-capture-page {
  min-height: 100vh;
  background: #020617;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: $spacing-xl $spacing-md;
}

.header-section {
  text-align: center;
  margin-bottom: $spacing-xl;
}

.icon-wrapper {
  width: 128rpx;
  height: 128rpx;
  border-radius: 50%;
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto $spacing-md;
}

.header-icon {
  font-size: 64rpx;
}

.header-title {
  font-size: $font-size-xl;
  color: $color-text-primary;
  font-weight: $font-weight-bold;
  display: block;
  margin-bottom: $spacing-sm;
}

.header-subtitle {
  font-size: $font-size-sm;
  color: rgba(255, 255, 255, 0.6);
}

.main-card {
  width: 100%;
  max-width: 600rpx;
  border-radius: 48rpx;
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  padding: $spacing-lg;
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.4);
  margin: 0 auto;
  
  // Desktop/Laptop styles
  // #ifdef H5
  @media (min-width: 768px) {
    max-width: 700px;
    border-radius: 24px;
    padding: 40px;
  }
  
  @media (min-width: 1024px) {
    max-width: 800px;
    padding: 50px;
  }
  // #endif
}

.upload-section {
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
}

.upload-area {
  aspect-ratio: 1.6 / 1;
  border-radius: 32rpx;
  border: 4rpx dashed rgba(255, 255, 255, 0.2);
  background: rgba(255, 255, 255, 0.05);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: $spacing-sm;
  margin-bottom: $spacing-lg;
  transition: all 0.3s ease;
}

.upload-area:active {
  border-color: rgba(250, 204, 21, 0.5);
  background: rgba(255, 255, 255, 0.1);
}

.upload-icon {
  font-size: 96rpx;
  color: rgba(255, 255, 255, 0.4);
  margin-bottom: $spacing-md;
}

.upload-text {
  font-size: $font-size-sm;
  color: rgba(255, 255, 255, 0.6);
  margin-bottom: 8rpx;
}

.upload-hint {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.4);
}

.action-btn {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: $spacing-sm;
  font-size: $font-size-base;
  font-weight: $font-weight-medium;
  transition: all 0.3s ease;
}

.action-btn.primary {
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  color: #020617;
  box-shadow: 0 4rpx 12rpx rgba(250, 204, 21, 0.4);
}

.action-btn.primary:active {
  transform: scale(0.98);
}

.action-btn.secondary {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: $color-text-primary;
}

.action-btn.secondary:active {
  background: rgba(255, 255, 255, 0.1);
}

.btn-icon {
  font-size: 40rpx;
}

.tips-card {
  padding: $spacing-md;
  border-radius: 24rpx;
  background: rgba(56, 189, 248, 0.1);
  border: 1px solid rgba(56, 189, 248, 0.2);
  margin-bottom: $spacing-md;
}

.tips-title {
  font-size: $font-size-xs;
  color: #38BDF8;
  display: block;
  margin-bottom: $spacing-sm;
}

.tips-list {
  display: flex;
  flex-direction: column;
  gap: 8rpx;
}

.tip-item {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.6);
}

.skip-btn {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  color: rgba(255, 255, 255, 0.6);
  font-size: $font-size-sm;
  transition: all 0.3s ease;
}

.skip-btn:active {
  color: $color-text-primary;
  background: rgba(255, 255, 255, 0.05);
}

.preview-section {
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
}

.preview-container {
  position: relative;
  aspect-ratio: 1.6 / 1;
  border-radius: 32rpx;
  overflow: hidden;
  background: rgba(0, 0, 0, 0.5);
  margin-bottom: $spacing-lg;
}

.preview-image {
  width: 100%;
  height: 100%;
}

.processing-overlay {
  position: absolute;
  inset: 0;
  background: rgba(2, 6, 23, 0.8);
  backdrop-filter: blur(4px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: $spacing-md;
}

.spinner {
  width: 128rpx;
  height: 128rpx;
  border: 8rpx solid rgba(250, 204, 21, 0.3);
  border-top-color: #FACC15;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.processing-content {
  display: flex;
  align-items: center;
  gap: $spacing-sm;
  color: #FACC15;
}

.sparkle-icon {
  font-size: 40rpx;
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.processing-text {
  font-size: $font-size-sm;
  color: #FACC15;
}

.processing-desc {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.4);
}

.preview-actions {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: $spacing-md;
}
</style>

// figma-import/src/components/onboarding/CardPhotoCapture.tsx
import { useState, useRef } from 'react';
import { Camera, Upload, Sparkles, X, Check, RotateCcw } from 'lucide-react';

interface CardPhotoCaptureProps {
  onPhotoCapture: (imageData: string) => void;
  onSkip: () => void;
}

export function CardPhotoCapture({ onPhotoCapture, onSkip }: CardPhotoCaptureProps) {
  const [capturedImage, setCapturedImage] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setCapturedImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleConfirm = () => {
    if (capturedImage) {
      setIsProcessing(true);
      // Simulate AI processing
      setTimeout(() => {
        onPhotoCapture(capturedImage);
      }, 2000);
    }
  };

  const handleRetake = () => {
    setCapturedImage(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="min-h-screen bg-[#020617] flex items-center justify-center px-4 py-8">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-br from-[#FACC15] to-[#38BDF8] mb-4">
            <Camera className="w-8 h-8 text-[#020617]" strokeWidth={1.5} />
          </div>
          <h1 className="text-white text-2xl mb-2">Capture Business Card</h1>
          <p className="text-white/60 text-sm">
            Take a photo of your business card or upload from gallery
          </p>
        </div>

        {/* Main Card */}
        <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-6 shadow-2xl">
          {!capturedImage ? (
            <>
              {/* Upload Area */}
              <div className="mb-6">
                <div
                  onClick={() => fileInputRef.current?.click()}
                  className="relative aspect-[1.6/1] rounded-2xl border-2 border-dashed border-white/20 bg-white/5 flex flex-col items-center justify-center cursor-pointer hover:border-[#FACC15]/50 hover:bg-white/10 transition-all"
                >
                  <Upload className="w-12 h-12 text-white/40 mb-3" strokeWidth={1.5} />
                  <p className="text-white/60 text-sm mb-1">Click to upload photo</p>
                  <p className="text-white/40 text-xs">or drag and drop</p>
                </div>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={handleFileSelect}
                  className="hidden"
                />
              </div>

              {/* Camera Button */}
              <button
                onClick={() => fileInputRef.current?.click()}
                className="w-full py-4 rounded-xl bg-gradient-to-r from-[#FACC15] to-[#38BDF8] text-[#020617] hover:opacity-90 transition-all shadow-lg flex items-center justify-center gap-2 mb-3"
              >
                <Camera className="w-5 h-5" strokeWidth={1.5} />
                <span className="font-medium">Take Photo</span>
              </button>

              {/* Upload Button */}
              <button
                onClick={() => fileInputRef.current?.click()}
                className="w-full py-4 rounded-xl bg-white/5 border border-white/10 text-white hover:bg-white/10 transition-all flex items-center justify-center gap-2 mb-4"
              >
                <Upload className="w-5 h-5" strokeWidth={1.5} />
                <span className="font-medium">Upload from Gallery</span>
              </button>

              {/* Tips */}
              <div className="rounded-xl bg-[#38BDF8]/10 border border-[#38BDF8]/20 p-4 mb-4">
                <p className="text-[#38BDF8] text-xs mb-2">📸 Tips for best results:</p>
                <ul className="text-white/60 text-xs space-y-1 list-disc list-inside">
                  <li>Ensure good lighting</li>
                  <li>Keep the card flat and in focus</li>
                  <li>Capture all text clearly</li>
                  <li>Avoid shadows and glare</li>
                </ul>
              </div>

              {/* Skip Button */}
              <button
                onClick={onSkip}
                className="w-full py-3 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-all"
              >
                <span className="text-sm">Skip - Enter Manually</span>
              </button>
            </>
          ) : (
            <>
              {/* Preview */}
              <div className="mb-6">
                <div className="relative aspect-[1.6/1] rounded-2xl overflow-hidden bg-black/50">
                  <img
                    src={capturedImage}
                    alt="Business card preview"
                    className="w-full h-full object-contain"
                  />
                  {isProcessing && (
                    <div className="absolute inset-0 bg-[#020617]/80 backdrop-blur-sm flex flex-col items-center justify-center">
                      <div className="relative w-16 h-16 mb-4">
                        <div className="absolute inset-0 border-4 border-[#FACC15]/30 rounded-full"></div>
                        <div className="absolute inset-0 border-4 border-[#FACC15] border-t-transparent rounded-full animate-spin"></div>
                      </div>
                      <div className="flex items-center gap-2 text-[#FACC15]">
                        <Sparkles className="w-5 h-5 animate-pulse" strokeWidth={1.5} />
                        <span className="text-sm">AI Processing...</span>
                      </div>
                      <p className="text-white/40 text-xs mt-2">Extracting information from card</p>
                    </div>
                  )}
                </div>
              </div>

              {!isProcessing && (
                <>
                  {/* Action Buttons */}
                  <div className="grid grid-cols-2 gap-3 mb-4">
                    <button
                      onClick={handleRetake}
                      className="py-3 px-4 rounded-xl bg-white/5 border border-white/10 text-white hover:bg-white/10 transition-all flex items-center justify-center gap-2"
                    >
                      <RotateCcw className="w-5 h-5" strokeWidth={1.5} />
                      <span className="text-sm">Retake</span>
                    </button>
                    <button
                      onClick={handleConfirm}
                      className="py-3 px-4 rounded-xl bg-gradient-to-r from-[#FACC15] to-[#38BDF8] text-[#020617] hover:opacity-90 transition-all flex items-center justify-center gap-2"
                    >
                      <Check className="w-5 h-5" strokeWidth={1.5} />
                      <span className="text-sm font-medium">Confirm</span>
                    </button>
                  </div>

                  {/* Cancel */}
                  <button
                    onClick={onSkip}
                    className="w-full py-3 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-all"
                  >
                    <span className="text-sm">Cancel - Enter Manually</span>
                  </button>
                </>
              )}
            </>
          )}
        </div>

        {/* AI Feature Badge */}
        <div className="mt-6 flex items-center justify-center gap-2 text-white/40">
          <Sparkles className="w-4 h-4" strokeWidth={1.5} />
          <span className="text-xs">Powered by AI Recognition</span>
        </div>
      </div>
    </div>
  );
}
