// src/pages/onboarding/ManualCardInput.vue
<template>
  <view class="manual-card-input-page">
    <!-- Header -->
    <view class="header-section">
      <text class="header-title">Create Your Card</text>
      <text class="header-subtitle">Enter your information to generate your AI-powered business card</text>
    </view>

    <!-- Main Form -->
    <view class="form-section">
      <!-- Personal Information -->
      <view class="form-card">
        <view class="card-header">
          <text class="card-icon">👤</text>
          <text class="card-title">Personal Information</text>
        </view>
        <view class="form-fields">
          <view class="field">
            <text class="field-label">Full Name <text class="required">*</text></text>
            <input v-model="formData.fullName" type="text" placeholder="Alex Tian Ye" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">Chinese Name (Optional)</text>
            <input v-model="formData.chineseName" type="text" placeholder="田野" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">Job Title <text class="required">*</text></text>
            <input v-model="formData.title" type="text" placeholder="Founder & CEO" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">Company <text class="required">*</text></text>
            <input v-model="formData.company" type="text" placeholder="Immedi.AI" class="field-input" />
          </view>
        </view>
      </view>

      <!-- Contact Information -->
      <view class="form-card">
        <view class="card-header">
          <text class="card-icon">📧</text>
          <text class="card-title">Contact Information</text>
        </view>
        <view class="form-fields">
          <view class="field">
            <text class="field-label">Email <text class="required">*</text></text>
            <input v-model="formData.email" type="email" placeholder="alex@immedi.ai" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">Phone <text class="required">*</text></text>
            <input v-model="formData.phone" type="tel" placeholder="+65 9876 5432" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">Website (Optional)</text>
            <input v-model="formData.website" type="url" placeholder="https://immedi.ai" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">Address (Optional)</text>
            <input v-model="formData.address" type="text" placeholder="Singapore" class="field-input" />
          </view>
          <view class="field">
            <text class="field-label">LinkedIn (Optional)</text>
            <input v-model="formData.linkedin" type="url" placeholder="linkedin.com/in/username" class="field-input" />
          </view>
        </view>
      </view>

      <!-- AI Enhancement -->
      <button class="ai-enhance-btn" :disabled="isAIEnhancing" @click="handleAIEnhance">
        <text class="sparkle-icon">✨</text>
        <text>{{ isAIEnhancing ? 'AI Enhancing...' : 'Enhance with AI Search' }}</text>
      </button>

      <!-- Submit Button -->
      <button class="submit-btn" @click="handleSubmit">
        <text>Continue to Customization</text>
        <text class="arrow-icon">→</text>
      </button>

      <!-- Back Button -->
      <button v-if="onBack" class="back-btn" @click="handleBack">
        <text>Back</text>
      </button>
    </view>

    <!-- Info -->
    <view class="info-card">
      <text class="info-icon">✨</text>
      <view class="info-content">
        <text class="info-title">AI Enhancement</text>
        <text class="info-text">Our AI will search for your professional information online to enrich your card with bio, expertise, and achievements.</text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  initialData?: any
}>()

const emit = defineEmits<{
  complete: [cardData: any]
  back: []
}>()

const isAIEnhancing = ref(false)

const formData = ref({
  fullName: props.initialData?.fullName || '',
  chineseName: props.initialData?.chineseName || '',
  title: props.initialData?.title || '',
  company: props.initialData?.company || '',
  email: props.initialData?.email || '',
  phone: props.initialData?.phone || '',
  website: props.initialData?.website || '',
  address: props.initialData?.address || '',
  linkedin: props.initialData?.linkedin || '',
})

const handleAIEnhance = () => {
  isAIEnhancing.value = true
  setTimeout(() => {
    isAIEnhancing.value = false
    uni.showToast({
      title: 'AI enhancement complete',
      icon: 'success',
    })
  }, 2000)
}

const handleSubmit = () => {
  if (!formData.value.fullName || !formData.value.title || !formData.value.company || !formData.value.email || !formData.value.phone) {
    uni.showToast({
      title: 'Please fill in all required fields',
      icon: 'none',
    })
    return
  }
  emit('complete', formData.value)
}

const handleBack = () => {
  emit('back')
}
</script>

<style lang="scss" scoped>
@import '../../styles/designTokens.scss';

.manual-card-input-page {
  min-height: 100vh;
  background: #020617;
  padding: $spacing-xl $spacing-md;
  padding-bottom: 192rpx;
}

.header-section {
  text-align: center;
  margin-bottom: $spacing-lg;
}

.header-title {
  font-size: $font-size-xl;
  color: $color-text-primary;
  font-weight: $font-weight-bold;
  display: block;
  margin-bottom: $spacing-sm;
}

.header-subtitle {
  font-size: $font-size-sm;
  color: rgba(255, 255, 255, 0.6);
}

.form-section {
  max-width: 600rpx;
  margin: 0 auto;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
  
  // Desktop/Laptop styles
  // #ifdef H5
  @media (min-width: 768px) {
    max-width: 700px;
  }
  
  @media (min-width: 1024px) {
    max-width: 800px;
  }
  // #endif
}

.form-card {
  padding: $spacing-lg;
  border-radius: 48rpx;
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.4);
}

.card-header {
  display: flex;
  align-items: center;
  gap: $spacing-sm;
  margin-bottom: $spacing-md;
}

.card-icon {
  font-size: 40rpx;
  color: #FACC15;
}

.card-title {
  font-size: $font-size-sm;
  color: $color-text-primary;
  font-weight: $font-weight-semibold;
}

.form-fields {
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
}

.field {
  display: flex;
  flex-direction: column;
  gap: $spacing-sm;
}

.field-label {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.6);
}

.required {
  color: #FACC15;
}

.field-input {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: $color-text-primary;
  font-size: $font-size-sm;
}

.field-input::placeholder {
  color: rgba(255, 255, 255, 0.4);
}

.ai-enhance-btn {
  width: 100%;
  padding: 18rpx 28rpx;
  border-radius: 24rpx;
  background: linear-gradient(135deg, rgba(56, 189, 248, 0.2) 0%, rgba(250, 204, 21, 0.2) 100%);
  border: 1px solid rgba(56, 189, 248, 0.3);
  color: $color-text-primary;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: $spacing-sm;
  font-size: $font-size-sm;
  transition: all 0.3s ease;
  min-height: 72rpx;
  box-sizing: border-box;
}

.ai-enhance-btn:disabled {
  opacity: 0.5;
}

.ai-enhance-btn:active {
  background: linear-gradient(135deg, rgba(56, 189, 248, 0.3) 0%, rgba(250, 204, 21, 0.3) 100%);
}

.sparkle-icon {
  font-size: 32rpx;
}

.submit-btn {
  width: 100%;
  padding: 18rpx 28rpx;
  border-radius: 24rpx;
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  color: #020617;
  font-size: $font-size-base;
  font-weight: $font-weight-medium;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: $spacing-sm;
  transition: all 0.3s ease;
  box-shadow: 0 4rpx 12rpx rgba(250, 204, 21, 0.4);
  min-height: 72rpx;
  box-sizing: border-box;
}

.submit-btn:active {
  transform: scale(0.98);
}

.arrow-icon {
  font-size: 40rpx;
}

.back-btn {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  color: rgba(255, 255, 255, 0.6);
  font-size: $font-size-sm;
  transition: all 0.3s ease;
}

.back-btn:active {
  color: $color-text-primary;
  background: rgba(255, 255, 255, 0.05);
}

.info-card {
  max-width: 600rpx;
  margin: $spacing-lg auto 0;
  padding: $spacing-md;
  border-radius: 24rpx;
  background: rgba(250, 204, 21, 0.1);
  border: 1px solid rgba(250, 204, 21, 0.2);
  display: flex;
  align-items: flex-start;
  gap: $spacing-sm;
}

.info-icon {
  font-size: 32rpx;
  color: #FACC15;
  margin-top: 4rpx;
  flex-shrink: 0;
}

.info-content {
  flex: 1;
}

.info-title {
  font-size: $font-size-xs;
  color: #FACC15;
  display: block;
  margin-bottom: 8rpx;
}

.info-text {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.6);
  line-height: 1.5;
}
</style>

// figma-import/src/components/onboarding/ManualCardInput.tsx
import { useState } from 'react';
import { User, Mail, Phone, Building2, Briefcase, Globe, MapPin, Sparkles, ArrowRight } from 'lucide-react';

interface ManualCardInputProps {
  onComplete: (cardData: any) => void;
  onBack?: () => void;
  initialData?: any;
}

export function ManualCardInput({ onComplete, onBack, initialData }: ManualCardInputProps) {
  const [isAIEnhancing, setIsAIEnhancing] = useState(false);
  const [formData, setFormData] = useState({
    fullName: initialData?.fullName || '',
    chineseName: initialData?.chineseName || '',
    title: initialData?.title || '',
    company: initialData?.company || '',
    email: initialData?.email || '',
    phone: initialData?.phone || '',
    website: initialData?.website || '',
    address: initialData?.address || '',
    linkedin: initialData?.linkedin || '',
  });

  const handleAIEnhance = () => {
    setIsAIEnhancing(true);
    // Simulate AI enhancement
    setTimeout(() => {
      setIsAIEnhancing(false);
      // AI could suggest taglines, extract company info, etc.
    }, 2000);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onComplete(formData);
  };

  const updateField = (field: string, value: string) => {
    setFormData({ ...formData, [field]: value });
  };

  return (
    <div className="min-h-screen bg-[#020617] px-4 py-8">
      <div className="max-w-md mx-auto">
        {/* Header */}
        <div className="text-center mb-6">
          <h1 className="text-white text-2xl mb-2">Create Your Card</h1>
          <p className="text-white/60 text-sm">
            Enter your information to generate your AI-powered business card
          </p>
        </div>

        {/* Main Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Personal Information */}
          <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-5 shadow-2xl">
            <div className="flex items-center gap-2 mb-4">
              <User className="w-5 h-5 text-[#FACC15]" strokeWidth={1.5} />
              <h2 className="text-white text-sm">Personal Information</h2>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-white/60 text-xs mb-2">
                  Full Name <span className="text-[#FACC15]">*</span>
                </label>
                <input
                  type="text"
                  value={formData.fullName}
                  onChange={(e) => updateField('fullName', e.target.value)}
                  placeholder="Alex Tian Ye"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#FACC15]/50 transition-all"
                  required
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">Chinese Name (Optional)</label>
                <input
                  type="text"
                  value={formData.chineseName}
                  onChange={(e) => updateField('chineseName', e.target.value)}
                  placeholder="田野"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#FACC15]/50 transition-all"
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">
                  Job Title <span className="text-[#FACC15]">*</span>
                </label>
                <input
                  type="text"
                  value={formData.title}
                  onChange={(e) => updateField('title', e.target.value)}
                  placeholder="Founder & CEO"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#FACC15]/50 transition-all"
                  required
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">
                  Company <span className="text-[#FACC15]">*</span>
                </label>
                <input
                  type="text"
                  value={formData.company}
                  onChange={(e) => updateField('company', e.target.value)}
                  placeholder="Immedi.AI"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#FACC15]/50 transition-all"
                  required
                />
              </div>
            </div>
          </div>

          {/* Contact Information */}
          <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-5 shadow-2xl">
            <div className="flex items-center gap-2 mb-4">
              <Mail className="w-5 h-5 text-[#38BDF8]" strokeWidth={1.5} />
              <h2 className="text-white text-sm">Contact Information</h2>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-white/60 text-xs mb-2">
                  Email <span className="text-[#FACC15]">*</span>
                </label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => updateField('email', e.target.value)}
                  placeholder="alex@immedi.ai"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#38BDF8]/50 transition-all"
                  required
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">
                  Phone <span className="text-[#FACC15]">*</span>
                </label>
                <input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => updateField('phone', e.target.value)}
                  placeholder="+65 9876 5432"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#38BDF8]/50 transition-all"
                  required
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">Website (Optional)</label>
                <input
                  type="url"
                  value={formData.website}
                  onChange={(e) => updateField('website', e.target.value)}
                  placeholder="https://immedi.ai"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#38BDF8]/50 transition-all"
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">Address (Optional)</label>
                <input
                  type="text"
                  value={formData.address}
                  onChange={(e) => updateField('address', e.target.value)}
                  placeholder="Singapore"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#38BDF8]/50 transition-all"
                />
              </div>

              <div>
                <label className="block text-white/60 text-xs mb-2">LinkedIn (Optional)</label>
                <input
                  type="url"
                  value={formData.linkedin}
                  onChange={(e) => updateField('linkedin', e.target.value)}
                  placeholder="linkedin.com/in/username"
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/40 focus:outline-none focus:border-[#38BDF8]/50 transition-all"
                />
              </div>
            </div>
          </div>

          {/* AI Enhancement */}
          <button
            type="button"
            onClick={handleAIEnhance}
            disabled={isAIEnhancing}
            className="w-full py-3 rounded-xl bg-gradient-to-r from-[#38BDF8]/20 to-[#FACC15]/20 border border-[#38BDF8]/30 text-white hover:bg-gradient-to-r hover:from-[#38BDF8]/30 hover:to-[#FACC15]/30 transition-all flex items-center justify-center gap-2"
          >
            <Sparkles className={`w-5 h-5 ${isAIEnhancing ? 'animate-pulse' : ''}`} strokeWidth={1.5} />
            <span className="text-sm">
              {isAIEnhancing ? 'AI Enhancing...' : 'Enhance with AI Search'}
            </span>
          </button>

          {/* Submit Button */}
          <button
            type="submit"
            className="w-full py-4 rounded-xl bg-gradient-to-r from-[#FACC15] to-[#38BDF8] text-[#020617] hover:opacity-90 transition-all shadow-lg flex items-center justify-center gap-2"
          >
            <span className="font-medium">Continue to Customization</span>
            <ArrowRight className="w-5 h-5" strokeWidth={1.5} />
          </button>

          {/* Back Button */}
          {onBack && (
            <button
              type="button"
              onClick={onBack}
              className="w-full py-3 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-all"
            >
              <span className="text-sm">Back</span>
            </button>
          )}
        </form>

        {/* Info */}
        <div className="mt-6 rounded-xl bg-[#FACC15]/10 border border-[#FACC15]/20 p-4">
          <div className="flex items-start gap-2">
            <Sparkles className="w-4 h-4 text-[#FACC15] mt-0.5 flex-shrink-0" strokeWidth={1.5} />
            <div>
              <p className="text-[#FACC15] text-xs mb-1">AI Enhancement</p>
              <p className="text-white/60 text-xs">
                Our AI will search for your professional information online to enrich your card with bio, expertise, and achievements.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
