// src/pages/onboarding/WelcomeSuccess.vue
<template>
  <view class="welcome-success-page">
    <view class="content-wrapper">
      <!-- Success Icon -->
      <view class="success-icon-wrapper">
        <view class="success-circle">
          <text class="check-icon">✓</text>
        </view>
        <text class="sparkle-icon">✨</text>
      </view>

      <!-- Welcome Message -->
      <text class="welcome-title">Welcome to MetaIC!</text>
      <text class="welcome-greeting">Hi {{ userName }} 👋</text>
      <text class="welcome-desc">Your AI-powered business card has been created successfully. Start networking smarter!</text>

      <!-- Feature Highlights -->
      <view class="features-card">
        <view class="feature-item">
          <view class="feature-icon-wrapper">
            <text class="feature-icon">✨</text>
          </view>
          <view class="feature-content">
            <text class="feature-title">AI-Powered Networking</text>
            <text class="feature-desc">Smart recommendations and auto-complete features</text>
          </view>
        </view>
        <view class="feature-item">
          <view class="feature-icon-wrapper">
            <text class="feature-icon">✓</text>
          </view>
          <view class="feature-content">
            <text class="feature-title">Easy Sharing</text>
            <text class="feature-desc">Share your card via QR code, link, or NFC</text>
          </view>
        </view>
        <view class="feature-item">
          <view class="feature-icon-wrapper">
            <text class="feature-icon">📱</text>
          </view>
          <view class="feature-content">
            <text class="feature-title">Contact Management</text>
            <text class="feature-desc">Organize and track your professional connections</text>
          </view>
        </view>
      </view>

      <!-- Continue Button -->
      <button class="continue-btn" @click="handleContinue">
        <text>Get Started</text>
        <text class="arrow-icon">→</text>
      </button>
    </view>
  </view>
</template>

<script setup lang="ts">
const emit = defineEmits<{
  continue: []
}>()

defineProps<{
  userName: string
}>()

const handleContinue = () => {
  emit('continue')
}
</script>

<style lang="scss" scoped>
@import '../../styles/designTokens.scss';

.welcome-success-page {
  min-height: 100vh;
  background: #020617;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: $spacing-xl $spacing-md;
}

.content-wrapper {
  width: 100%;
  max-width: 600rpx;
  text-align: center;
  margin: 0 auto;
  
  // Desktop/Laptop styles
  // #ifdef H5
  @media (min-width: 768px) {
    max-width: 700px;
  }
  
  @media (min-width: 1024px) {
    max-width: 800px;
  }
  // #endif
}

.success-icon-wrapper {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  margin-bottom: $spacing-xl;
}

.success-circle {
  width: 256rpx;
  height: 256rpx;
  border-radius: 50%;
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  padding: 8rpx;
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.05); }
}

.check-icon {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  background: #020617;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 128rpx;
  color: #FACC15;
  font-weight: $font-weight-bold;
}

.sparkle-icon {
  position: absolute;
  right: -32rpx;
  top: -32rpx;
  font-size: 80rpx;
  color: #38BDF8;
  animation: bounce 2s ease-in-out infinite;
}

@keyframes bounce {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-20rpx); }
}

.welcome-title {
  font-size: 60rpx;
  color: $color-text-primary;
  font-weight: $font-weight-bold;
  display: block;
  margin-bottom: $spacing-md;
}

.welcome-greeting {
  font-size: $font-size-base;
  color: rgba(255, 255, 255, 0.6);
  display: block;
  margin-bottom: $spacing-sm;
}

.welcome-desc {
  font-size: $font-size-sm;
  color: rgba(255, 255, 255, 0.6);
  display: block;
  margin-bottom: $spacing-xl;
  max-width: 480rpx;
  margin-left: auto;
  margin-right: auto;
  line-height: 1.5;
}

.features-card {
  padding: $spacing-lg;
  border-radius: 48rpx;
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.4);
  margin-bottom: $spacing-xl;
  display: flex;
  flex-direction: column;
  gap: $spacing-md;
}

.feature-item {
  display: flex;
  align-items: flex-start;
  gap: $spacing-md;
  text-align: left;
}

.feature-icon-wrapper {
  width: 80rpx;
  height: 80rpx;
  border-radius: 50%;
  background: rgba(250, 204, 21, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.feature-icon {
  font-size: 40rpx;
  color: #FACC15;
}

.feature-content {
  flex: 1;
}

.feature-title {
  font-size: $font-size-sm;
  color: $color-text-primary;
  font-weight: $font-weight-semibold;
  display: block;
  margin-bottom: 8rpx;
}

.feature-desc {
  font-size: $font-size-xs;
  color: rgba(255, 255, 255, 0.6);
  line-height: 1.5;
}

.continue-btn {
  width: 100%;
  padding: $spacing-md;
  border-radius: 24rpx;
  background: linear-gradient(135deg, #FACC15 0%, #38BDF8 100%);
  color: #020617;
  font-size: $font-size-base;
  font-weight: $font-weight-medium;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: $spacing-sm;
  transition: all 0.3s ease;
  box-shadow: 0 4rpx 12rpx rgba(250, 204, 21, 0.4);
}

.continue-btn:active {
  transform: scale(0.98);
}

.arrow-icon {
  font-size: 40rpx;
}
</style>

// figma-import/src/components/onboarding/WelcomeSuccess.tsx
import { CheckCircle, Sparkles, ArrowRight } from 'lucide-react';

interface WelcomeSuccessProps {
  userName: string;
  onContinue: () => void;
}

export function WelcomeSuccess({ userName, onContinue }: WelcomeSuccessProps) {
  return (
    <div className="min-h-screen bg-[#020617] flex items-center justify-center px-4 py-8">
      <div className="w-full max-w-md text-center">
        {/* Success Icon */}
        <div className="relative inline-flex items-center justify-center mb-8">
          <div className="w-32 h-32 rounded-full bg-gradient-to-br from-[#FACC15] to-[#38BDF8] p-1 animate-pulse">
            <div className="w-full h-full rounded-full bg-[#020617] flex items-center justify-center">
              <CheckCircle className="w-16 h-16 text-[#FACC15]" strokeWidth={1.5} />
            </div>
          </div>
          <div className="absolute -right-2 -top-2">
            <Sparkles className="w-10 h-10 text-[#38BDF8] animate-bounce" strokeWidth={1.5} />
          </div>
        </div>

        {/* Welcome Message */}
        <h1 className="text-white text-3xl mb-3">Welcome to MetaIC!</h1>
        <p className="text-white/60 text-base mb-2">Hi {userName} 👋</p>
        <p className="text-white/60 text-sm mb-8 max-w-sm mx-auto">
          Your AI-powered business card has been created successfully. Start networking smarter!
        </p>

        {/* Feature Highlights */}
        <div className="rounded-[24px] bg-[#0F172A]/80 backdrop-blur-xl border border-white/10 p-6 shadow-2xl mb-8">
          <div className="space-y-4">
            <div className="flex items-start gap-3 text-left">
              <div className="w-10 h-10 rounded-full bg-[#FACC15]/20 flex items-center justify-center flex-shrink-0">
                <Sparkles className="w-5 h-5 text-[#FACC15]" strokeWidth={1.5} />
              </div>
              <div>
                <h3 className="text-white text-sm mb-1">AI-Powered Networking</h3>
                <p className="text-white/60 text-xs">Smart recommendations and auto-complete features</p>
              </div>
            </div>

            <div className="flex items-start gap-3 text-left">
              <div className="w-10 h-10 rounded-full bg-[#38BDF8]/20 flex items-center justify-center flex-shrink-0">
                <CheckCircle className="w-5 h-5 text-[#38BDF8]" strokeWidth={1.5} />
              </div>
              <div>
                <h3 className="text-white text-sm mb-1">Easy Sharing</h3>
                <p className="text-white/60 text-xs">Share your card via QR code, link, or NFC</p>
              </div>
            </div>

            <div className="flex items-start gap-3 text-left">
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-[#FACC15]/20 to-[#38BDF8]/20 flex items-center justify-center flex-shrink-0">
                <span className="text-xl">📱</span>
              </div>
              <div>
                <h3 className="text-white text-sm mb-1">Contact Management</h3>
                <p className="text-white/60 text-xs">Organize and track your professional connections</p>
              </div>
            </div>
          </div>
        </div>

        {/* Continue Button */}
        <button
          onClick={onContinue}
          className="w-full py-4 rounded-xl bg-gradient-to-r from-[#FACC15] to-[#38BDF8] text-[#020617] hover:opacity-90 transition-all shadow-lg flex items-center justify-center gap-2"
        >
          <span className="font-medium">Get Started</span>
          <ArrowRight className="w-5 h-5" strokeWidth={1.5} />
        </button>
      </div>
    </div>
  );
}
